### ISSUE TITLE
Any chance of making it so vendors can't buy out each other's stock just to mark it up?

### ISSUE THREAD

**Issue by OldKingSol** [PurelyAliyah/Outsider#22]
Reposting on suggesting of Aliyah to move it to suggestion area, not to be redundant.

<original post>

I've had this happen several times, now, and I'm pretty much done with having a shop if it's just how it's going to be. I like to make my prices as low as I can, but then some greedy vendors buy me out and sell my stock at a higher price. I go through the bother of putting together and maintaining a stock - for _players_. People who need to buy something once in awhile, or whatever. Not for vendors to get greedy and buy out my entire stock so they can make a profit. I'm a little sick of it, and if there's nothing that can be done, then I'd just like to respectfully request removal of my warp/shop.

</original post>

<addition to original post>

For my own part, I'd think that -could- be considered a type of griefing, if nothing else.

</addition to original post>

Thanks for your time & consideration. Will delete miscategorized post if able.

**Comment by PurelyAliyah** [comment]
Thank you for moving your post. I will look into this as soon as I get a chance.

**Comment by OldKingSol** [comment]
K. As for the removing my warp/shop, never mind that part. I've decided to work around it in the mean time, and will just stop selling those things that have been most problematic.
