### ISSUE TITLE
Exchanging votes/encouraging votes beyond Outsider status

### ISSUE THREAD

**Issue by OldKingSol** [PurelyAliyah/Outsider#24]
Would it be feasible to allow folks to exchange votes for in-game cash? For instance, if you're at 200 votes, you can convert 20 of them into, say (just for example), $5000, so your rank would go back down to whatever 180 votes is. It's just a thought for encouraging voting even more than the ranks already do.

I also have a thought regarding Outsider status and voting. Once you get there, the only motivation to vote is to support the server. That's great, and I know I do, but it's easy to forget. Maybe, because the rank is so chock-full of benefits, 'charge' folks a few votes a month to maintain it. Just a thought.

I'm sure if there are many cons to these ideas that I'm not thinking of, someone will enlighten. It was just a couple of thoughts, anyways. L8r! :-)

**Comment by PurelyAliyah** [comment]
Its a thought I might be able to make a command block system to do this Possibly but I would have to look into it, that might be something for a future rank wipe

**Comment by PurelyAliyah** [comment]
I'm just not sure If I'm going to be able to do this honestly
