### ISSUE TITLE
Shops (No permission)

### ISSUE THREAD

**Issue by OneBigFamily** [PurelyAliyah/Outsider#35]
I/we can't use the shops.
"No permission" error when clicking the signs.
I know that MrsChipsy already said that but I want to report it here as well just in case.

/Jerry - 161123

![error](https://cloud.githubusercontent.com/assets/24221075/20665241/1bdda992-b55f-11e6-91f8-5036bc099c35.jpg)

**Comment by ZephyrXZ** [comment]
Will look into it if not solved by the time i get home.
