### ISSUE TITLE
Invincible invisible cows (issue)

### ISSUE THREAD

**Issue by OneBigFamily** [PurelyAliyah/Outsider#37]
There was an issue this morning with invisible and invincible mob standing in the way of building for other players. Now, there's an issue again at Samb0z0s place. They can't be killed and Sam had to use the kill command to get rid of it.

**Comment by OneBigFamily** [comment]
Samb0z0's issue got solved, but it still stands. Something must cause it?

**Comment by PurelyAliyah** [comment]
The Cow is from the corpse plugin, It makes it where players are able to open the corpse.
