### ISSUE TITLE
Potential New Plugin

### ISSUE THREAD

**Issue by PurelyAliyah** [PurelyAliyah/Outsider#48]
https://www.spigotmc.org/resources/pickupmoney.11334/

**Comment by OneBigFamily** [comment]
Oh my god, yes.

**Comment by ZephyrXZ** [comment]
Rpg... Rip

**Comment by Madpaddy98** [comment]
My God that would be brilliant for the server and could be very benefitial to players and would promote them doing things like killing mobs and mining eg.
