### ISSUE TITLE
/setflag /thru not working

### ISSUE THREAD

**Issue by shinchad** [PurelyAliyah/Outsider#53]
Basically, going on from what Jerry said, the plugin with /setflag doesn't seem to exist anymore, since it's gone and that's why mobs were spawning in spawn. I only noticed cause they were spawning in my house where I had set a flag for them to not. :)

**Comment by PurelyAliyah** [comment]
We don't have the /setflag plugin and haven't had it for a month. Please don't make duplicate issues this is already and a problem and I am very well aware about it. :P
