### ISSUE TITLE
More Mobs + Custom terrain + New Dungeon plugin 

### ISSUE THREAD

**Issue by Mikeofwind** [PurelyAliyah/Outsider#56]
https://www.spigotmc.org/resources/more-mobs-new-mobs-and-now-with-gui-1-8-1-9-1-10-1-11-3000-downloads.17930/

The more mobs plugin add the server new mobs and it could be great for this server so that way everyone can have fun killing those new mobs.

The other plugin is the custom terrain plugin where you can edit biomes to make it realistic 

https://www.spigotmc.org/resources/terraincontrol.2214/

And finally this plugin added new dungeons! 

https://www.spigotmc.org/resources/dungeonsxl.9488/

**Comment by ZephyrXZ** [comment]
Thanks for the suggestion, Will go through it at a suiting time.

**Comment by PurelyAliyah** [comment]
No. Thanks for the suggestion.
