### ISSUE TITLE
Move all of your questions to the website please.

### ISSUE THREAD

**Issue by tanmar123** [PurelyAliyah/Outsider#61]
please remove this - its preventing me from asking how i access my reset vault. i cant ask my questions and when i do im told to go to the website - but my question isnt awnsered there either.
dont awnser here because chances are i wont respond as i am very inactive on GitHub.

please remove this plugin as its causing me, and probably many others alot of trouble.

thanks 
-tanmar123 (my minecraft IGN)

**Comment by ZephyrXZ** [comment]
No, 1. I have no idea what you are talking about because you are insanely unorganized. 
2. Its there for a reason.
3. This isnt a plugin.
4. No we're not removing it because it keeps our issues organized.
5. Its not preventing you to do anything if its GitHub you are talking about.
