### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by TD5update** [PurelyAliyah/Outsider#64]
My IGN is TD5update and i have been having some strange issues. First, I put down some doors and they disappear when i come back to them later. The thing is, it isn't lag. the chat was perfectly normal and moved at normal speed. When i used /home to return to my home, my house wasn't there and the town around it disappeared. I lost a total of 6 double chests of stuff. Not only did it all disappear it actually reverted to the original terrain. I immediately alerted moderator Jerbear and he was able to see that it had disappeared as well. He told me to create a ticket but i couldn't. This wasn't lag either since i actually got an error message back. I tried to relog but i couldn't reconnect and it always says that I timed out.

**Comment by ZephyrXZ** [comment]
Its like this for everyone, there are corrupted chunks which corrupt the server, which leads to these issues. Sorry for the terrible inconvienence, it wont happen once the reset done.
