### ISSUE TITLE
Suggestion - Homes

### ISSUE THREAD

**Issue by NomSTee** [PurelyAliyah/Outsider#66]
-Story time version-
So i was thinking to myself and i came across an idea that could enhance SMP on the server. I asked myself the question why do people play on multiplayer servers that are still fairly vanilla, is it because of the plugins? yes, but not really.. I believe it is because of the social aspect of multiplayer, the fact you can build something amazing and not have it go unnoticed, talk to people who may have similar interests to you and 
enjoy the fact that you're not alone :P 
So, enough with the teasing. The idea i was thinking of is giving players the ability to make a public home so that people can visit, Like a player warp but outside of the general "warps" created by the server. Perhaps the number of public warps you can have depend on your rank or everyone could have 1 public warp if they pass a rank and that's the only warp they recieve. For further info ill be stating in the other version and repeating a few things.

-Straight to the point version-
Public homes/public player warps. These warps will be outside of the general "warps" created by the server and will be in a new list specifically for player warps. To avoid spam of these warps you can limit the amount players have and perhaps give them a new public warp everytime they pass a number of ranks or you could simply give players one but i'd advise not giving players ranked 1 - 4 in the ranking system as that could cause spam of useless public warps. 

Pros:
- Allows players to share their home or builds to people on the server
- Bored players can simply visit peoples houses and perhaps gain some inspriration from their builds
- Players can connect better with fellow players

Cons:

- People might share warps of hard to find places and players will not appreciate finding something rare.
- People might make a warp to a mob farm which could give new players a headstart in the economy BUT this could be prevented with a rule and im sure it'll give staff who have nothing to do something to do as they can explore different player warps.

Plugins i believe to fit what i've described (simply to save you from doing research yourself ;) )
https://www.spigotmc.org/resources/warppoint.33986/

There are others but they are outdated and i've read why you didn't update to 1.11 quickly.. so i understand if you'd prefer not to but they do exactly what i suggested and perhaps if you play around with it on a test server. I don't believe it will cause problems as it is simply teleporting so it's nothing the new updates have really changed. 
https://dev.bukkit.org/projects/playerwarp
and
https://dev.bukkit.org/projects/mywarp

Please do consider these 2 last ones as I believe they will still work as nothing has been changed with teleporting since they were created.. But test them first, do not take my word on this.

THIS IS THE END DON'T WORRY! NO MORE READING FOR YOU <3

Jk there's more
No actually there isn't you can stop reading now cause it's pointless at this point
Actually, it's not pointless... i matter, k?
i....... Im done. :)

**Comment by NomSTee** [comment]
Okay, i just heard that apparently you can submit a request to have a warp set somewhere... But i believe it would be better if the warps were outside of the general server warps.

**Comment by NomSTee** [comment]
If you guys are busy with other projects then you can post pone this idea if you want or even forget about it, i won't mind. I just don't want to burden you guys with more to do.

**Comment by PurelyAliyah** [comment]
Actually! This is already being set up, I just haven't had time to implement it, I've been trying to get the plugin to work properly for weeks but it's been bugging out! Thank you for the suggestion though :P Buttt I'm already working on this.
