### ISSUE TITLE
Suggestion: News

### ISSUE THREAD

**Issue by NomSTee** [PurelyAliyah/Outsider#67]
it would be cool to add variety to the news announcements! Here are some ideas i had.
my ideas of what you coud do to add variety. Ill put a list of ideas here:
- Quote of the day
- What you ate for breakfast, lunch, dinner ect (People need to know)
- Real world news
- Funny jokes (Please make them funny not like... "Knock Knock, who's there? Orange, Orange who? Orange you gonna let me in?) OR MAKE THEM SO UNFUNNY THAT THEY BECOME SUPER FUNNY! 
- peoples birthdays
- In game news like "Ronald Mcdonald just opened up a shop called KFC"
- People could pay to be in the news, kind of like an advertisement (I don't really reccomend this as it could be spammy but its an idea)
- Thanking people who donated that day
- The weather and the temperature (Of course you'd have to pick a place, but i say choose the place where the server is located) 
- Your ideas :)

Just a side note:
I was listening to 

- Clarity - Zedd, Foxes
- Rude - MAGIC!
- Worth it - Fifth Harmony, Kid Ink

while typing this :)

**Comment by PurelyAliyah** [comment]
Well As great as an idea as that is (And I might actually do this depending on how I think) It would also get somewhat spammy on the home page, and most announcements could be lost


BUT, In saying that, It could also bring more potential to the website and this isn't an idea I hate. Thank you for not annoying me with ideas that aren't new/or have been stated I won't do a million times. 

^ I'm not insulting you, I'm insulting everyone else. It's fineee. I'll talk to the Co-Owners about it, See what their opinions are and see if it makes it to the Council on a yes or no decision.
